### ISSUE TITLE
UUID instead of make_ref for unique_folder

### ISSUE THREAD

**Issue by hunterboerner** [rabbit-ci/rabbit-ci#17]
`unique_folder` is being used to generate a unique temporary folder. I would prefer to use UUIDs over the `make_ref` and node/time nonsense that is being used right now.

**Comment by hunterboerner** [comment]
@mtanzi this should be a fairly easy change if you want to take a crack at it. The unique_folder function is defined on `feature/new-builder` [here](https://github.com/rabbit-ci/backend/blob/feature/new-builder/apps/build_man/lib/build_man/file_helpers.ex#L2-L11) and this Elixir package can be used for UUID generation (I think v4 is what we want): https://github.com/zyro/elixir-uuid.

Do you think you could make this change?

**Comment by mtanzi** [comment]
Hi @hunterboerner ! Yes the change makes totally sense and it looks straightforward. I'll give it a go! :)

**Comment by hunterboerner** [comment]
In feature/new-builder
